name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Build all Maven modules
      - name: Build Maven modules
        run: mvn clean package -DskipTests

      # Build Docker image for transaction-service
      - name: Build Docker image for transaction-service
        run: |
          docker build -t transaction-service:latest -f transaction-service/Dockerfile .

      # Build Docker image for user-service
      - name: Build Docker image for user-service
        run: |
          docker build -t user-service:latest -f user-service/Dockerfile .

      # Build Docker image for exchange-rate-service
      - name: Build Docker image for exchange-rate-service
        run: |
          docker build -t exchange-rate-service:latest -f exchange-rate-service/Dockerfile .

      # Build Docker image for wallet-service
      - name: Build Docker image for wallet-service
        run: |
          docker build -t wallet-service:latest -f wallet-service/Dockerfile .
          

      # Push Docker images to Docker Hub (optional)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push transaction-service Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/transaction-service:latest

      - name: Push user-service Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/user-service:latest

      - name: Push exchange-rate-service Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/exchange-rate-service:latest

      - name: Push wallet-service Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/wallet-service:latest
